// src/styles.js
export const styles = {
  app: {
    backgroundColor: '#12121a',
    minHeight: '100vh',
    color: '#e0e0e0',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    backgroundImage: `
      linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)
    `,
    backgroundSize: '30px 30px',
  },
  header: {
    padding: '40px 20px',
    textAlign: 'center',
  },
  appName: {
    fontSize: '2.5rem',
    fontWeight: '600',
    letterSpacing: '1px',
    color: '#ffffff',
    cursor: 'pointer',
  },
  tagline: {
    fontSize: '1rem',
    color: '#a0a0c0',
    marginTop: '10px',
    fontWeight: '300',
  },
  landingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    textAlign: 'center',
  },
  introduction: {
    maxWidth: '800px',
    fontSize: '1.1rem',
    lineHeight: '1.6',
    color: '#c0c0e0',
    marginBottom: '40px',
  },
  categoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '25px',
    width: '100%',
    maxWidth: '1200px',
    marginTop: '30px',
  },
  categoryCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: '15px',
    padding: '40px 20px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'transform 0.3s ease, background-color 0.3s ease',
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#ffffff',
  },
  controlsContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '20px',
    marginBottom: '30px',
    padding: '20px',
    position: 'sticky',
    top: 0,
    backgroundColor: 'rgba(18, 18, 26, 0.85)',
    backdropFilter: 'blur(10px)',
    zIndex: 999,
  },
  backButton: {
    fontSize: '1rem',
    padding: '12px 20px',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: '#ffffff',
    cursor: 'pointer',
  },
  searchBar: {
    fontSize: '1.1rem',
    padding: '12px 15px',
    width: '50%',
    maxWidth: '500px',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: '#ffffff',
  },
  sortDropdown: {
    fontSize: '1rem',
    padding: '12px',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: '#ffffff',
  },
  sortOption: {
    backgroundColor: '#1a1a2e',
    color: '#e0e0e0',
  },
  productList: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '25px',
    padding: '20px',
  },
  productCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: '15px',
    padding: '25px',
    width: '320px',
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'column',
    cursor: 'pointer',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  productName: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: '#ffffff',
    marginTop: 0,
    minHeight: '45px',
    flexGrow: 1,
  },
  brandName: {
    fontSize: '0.9rem',
    color: '#a0a0c0',
    marginBottom: '15px',
  },
  scoresContainer: {
    borderTop: '1px solid rgba(255, 255, 255, 0.2)',
    paddingTop: '15px',
  },
  scoreItem: {
    display: 'grid',
    gridTemplateColumns: '110px 1fr 40px',
    alignItems: 'center',
    fontSize: '0.9rem',
    marginBottom: '8px',
  },
  scoreLabel: { color: '#e0e0e0' },
  scoreValue: { fontWeight: '600', textAlign: 'right', color: '#e0e0e0' },
  scoreBarContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: '10px',
    height: '8px',
    overflow: 'hidden',
  },
  modalOverlay: {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'rgba(30, 30, 50, 0.9)',
    backdropFilter: 'blur(20px)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    padding: '30px',
    borderRadius: '15px',
    width: '90%',
    maxWidth: '600px',
    textAlign: 'left',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  modalCloseButton: {
    backgroundColor: '#e94560',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    cursor: 'pointer',
    fontWeight: '600',
  },
  aiSummarySection: {
    marginTop: '20px',
    paddingTop: '15px',
    borderTop: '1px solid rgba(255, 255, 255, 0.2)',
  },
  aiSummaryText: {
    fontSize: '1rem',
    lineHeight: '1.6',
    color: '#c0c0e0',
    fontStyle: 'italic',
  },
  reviewsSection: {
    marginTop: '20px',
    borderTop: '1px solid rgba(255, 255, 255, 0.2)',
    paddingTop: '15px',
  },
  reviewCard: {
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '10px',
    padding: '15px',
    marginBottom: '10px',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  reviewAuthor: {
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: '5px',
  },
  reviewText: {
    fontSize: '0.9rem',
    lineHeight: '1.4',
    color: '#c0c0e0',
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '30px',
  },
  askButton: {
    backgroundColor: '#00f5d4',
    color: '#1a1a2e',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'transform 0.2s ease',
  },
  chatbotToggleContainer: {
    position: 'fixed',
    bottom: '30px',
    right: '30px',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  chatbotToggleButton: {
    backgroundColor: '#00f5d4',
    color: '#12121a',
    border: 'none',
    borderRadius: '50%',
    width: '60px',
    height: '60px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 5px 20px rgba(0, 245, 212, 0.3)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
  },
  chatHint: {
    backgroundColor: 'white',
    color: '#12121a',
    padding: '10px 15px',
    borderRadius: '8px',
    boxShadow: '0 5px 15px rgba(0,0,0,0.2)',
    display: 'flex',
    alignItems: 'center',
    whiteSpace: 'nowrap',
    animation: 'fadeInUp 0.5s ease-out forwards',
    fontWeight: '500',
  },
  chatHintClose: {
    background: 'none',
    border: 'none',
    color: '#12121a',
    marginLeft: '10px',
    cursor: 'pointer',
    fontSize: '1.2rem',
    fontWeight: 'bold',
  },
  chatbotContainer: {
    position: 'absolute',
    bottom: '0',
    right: '0',
    width: '320px',
    height: '450px',
    backgroundColor: '#2c2c54',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 1001,
    animation: 'fadeInUp 0.3s ease-out',
  },
  chatbotHeader: {
    padding: '15px',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  chatbotClose: {
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '1.5rem',
    cursor: 'pointer',
  },
  chatbotBody: {
    flexGrow: 1,
    padding: '15px',
    overflowY: 'auto',
  },
  userMessage: {
    textAlign: 'right',
    backgroundColor: '#00f5d4',
    color: '#1a1a2e',
    padding: '10px',
    borderRadius: '15px 15px 0 15px',
    marginBottom: '10px',
    maxWidth: '80%',
    marginLeft: 'auto',
  },
  aiMessage: {
    textAlign: 'left',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: '10px',
    borderRadius: '15px 15px 15px 0',
    marginBottom: '10px',
    maxWidth: '80%',
    marginRight: 'auto',
  },
  chatbotInputArea: {
    display: 'flex',
    padding: '10px',
    borderTop: '1px solid rgba(255, 255, 255, 0.2)',
  },
  chatbotInput: {
    flexGrow: 1,
    border: 'none',
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderRadius: '15px',
    padding: '10px 15px',
    color: 'white',
  },
  chatbotSendButton: {
    background: '#00f5d4',
    border: 'none',
    color: '#1a1a2e',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    marginLeft: '10px',
    cursor: 'pointer',
    fontSize: '1.2rem',
  },
};
